version: "3.4"
services:
  nodejs: # docker run -it -v ${PWD}:/work -w /work -p 5002:5000 facp/nodejs:1.0.0 /bin/sh
    container_name: nodejs
    image: facp/nodejs:1.0.0
    build:
      context: ./nodejs
      target: debug
    #working_dir: /work   #comment out for build.target:prod
    #entrypoint: /bin/sh  #comment out for build.target:prod
    #stdin_open true      #comment out for build.target:prod
    #tty: true
    volumes:
      - ./nodejs/src/:/work/src/
    ports:
      - 5002:5000
      - 9229:9229      